image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

matrix:
  fast_finish: true

# skip unsupported combinations
init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - echo %generator%

before_build:
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -G %generator%

build:
  project: build/TP_Grammaire-Langage.sln
  parallel: true

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false