image:
  - Visual Studio 2015

matrix:
  fast_finish: true

environment:
  matrix:
    - target: mingw
    - target: vs

# skip unsupported combinations
init:
  - SET PATH=C:\MinGW\bin;%PATH%
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013%arch%" )
  - if "%target%"=="mingw" ( set generator="MinGW Makefiles" )
  - echo %generator%

before_build:
  - mkdir build
  - cd build
  - cmake --version
  - if "%target%"=="vs" ( cmake .. -G %generator% )
  - if "%target%"=="mingw" ( cmake .. -G %generator% -DCMAKE_SH="CMAKE_SH-NOTFOUND")

build_script:
  - if "%target%"=="mingw" ( C:\MinGW\bin\mingw32-make.exe )
  - if "%target%"=="vs" ( msbuild TP_Grammaire-Langage.sln )

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
